### ISSUE TITLE
Private apps

### ISSUE THREAD

**Issue by harberg** [christophergregory/shopify-node-api#28]
Hello,

I am learning how to build a private app and on the auth_url I am getting an error that "Oauth error invalid_request: The Shopify API application does not support oauth"

Is there something that I am missing that is different for private apps vs public apps?

Thanks for your help.

**Comment by nodeit** [comment]
The module will work for both private and public apps, the difference in the setup is that you do not need to go through the oauth process for private apps since you are already provided with the shops api key and token.

I'm assuming you are trying to create a private app, check out the documentation here: https://github.com/christophergregory/shopify-node-api#note

**Comment by harberg** [comment]
Thank you very much.
