### ISSUE TITLE
exchange_temporary_token requires state parameter to be present

### ISSUE THREAD

**Issue by mariusa** [christophergregory/shopify-node-api#47]
Sometimes, Shopify doesn't pass the state parameter as a query string, even though it is set in the authorize call.
Several others reported this:
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/oauth2-state-parameter-is-not-passed-262706
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/oauth-state-parameter-207445

In this case, it's impossible to use exchange_temporary_token(), as that forces check of the state
```
   if (!self.is_valid_signature(query_params)) {
        return callback(new Error("Signature is not authentic!"));
    }
```

Would it be possible to ignore that instead, e.g.
```
   if (!self.is_valid_signature(query_params, true)) {
```
and let developers call is_valid_signature(query_params) if desired?

Thanks

**Comment by mozeryansky** [comment]
I don't think the a library which implements OAuth 2, like shopify-node-api, should ignore the state param if it was passed. As it says in the specification [http://tools.ietf.org/html/rfc6749#section-4.1.1](http://tools.ietf.org/html/rfc6749#section-4.1.1): 

> state
         REQUIRED if the "state" parameter was present in the client
         authorization request.  The exact value received from the
         client.

Shopify not passing the state back is invalid OAuth 2, and the library should deny the requests. The error is with Shopify, not the library. I do see that Shopify is sometimes slow or unresponsive to requests made on the forums.

Instead of waiting for Shopify (although the state is passed for me at this time), I would recommend you verify the request manually, if it fails verify it manually without a nonce, then use which ever ShopifyAPI object worked to then call exchange_temporary_token. But you really should make note of you doing this remove this hotfix if the state param is working for you to be OAuth 2 compliant.

It would look something like this: (But please don't actually do this in prod)

```
// create like you normally would
var Shopify = new shopifyAPI({...., nonce: EXPECTED_NONCE});

// TODO: remove if Shopify does pass 'state'
// manually verify
if (!Shopify.is_valid_signature(query_params)) {
    // if it fails, create without a nonce
    Shopify = new shopifyAPI({...., nonce: undefined});// or don't include it
}

// use like you normally would
Shopify.exchange_temporary_token(...)
```
