### ISSUE TITLE
Are there any sample apps made with this?

### ISSUE THREAD

**Issue by AdityaAnand1** [christophergregory/shopify-node-api#83]
I was just wondering if there were any complete open source app examples made with this, it would certainly help us get up to speed quickly :)

**Comment by nodeit** [comment]
@AdityaAnand1, this module get's downloaded 5000k+ times per month so I'm sure there are 100s if not thousands of apps built using it. However, these tend not to be open sourced either because they are proprietary or built for bespoke use cases. 

If I was aware of any open source examples I would point you in that direction but unfortunately I do not. Apologies for the inconvenience.
